### ISSUE TITLE
Decide on how to attach DOS to the ORT process

### ISSUE THREAD

**Issue by Etsija** [doubleopen-project/dos#60]
### Our understanding of the current process of scanning an application with ORT

1. User runs ORT Analyzer for the whole packet -> analyzer-result.yml
2. User has a .ort.yml file in the application root folder with

```
excludes:
  scopes:
  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

```
3. User runs `ort scan -i ... -o ... --skip-excluded`.  This in effect excludes all devDependencies from the scanning phase. For example, for mime_types project, the ORT Analyzer results in hundreds of packages. Out of these, only three packages are sent to ScanCode, and ScanCode returns the scan results for only these three packets

### How and where to interrupt this process with DOS concept?

By looking at analyzer-result.yml, it is not clear as to how the ort scan phase decides which of the packets to send to ScanCode, as there seems to be no such info on packet data in that file, to decide on exclusion or inclusion of a particular packet.

In practise, we need a way to "interrupt" the usual code analysing process in such a way that after the user has run the ORT Analyzer and sends the resulting analyzer-result.yml to DOS, DOS can decide which of the hundreds of packets are considered as candidates for scanning process.

In a nutshell: from ORT Analyzer results, how can the devDependencies (or, more generally, any packet the user wants to) be excluded from the scanning phase?

**Comment by willebra** [comment]
We should keep running the ORT scanner command, however, DOS should be configured as an optional scanner for ORT. For this, an ORT scanner class should be created. For reference here is the scancode scanner class: https://github.com/oss-review-toolkit/ort/blob/main/scanner/src/main/kotlin/scanners/scancode/ScanCode.kt

This is important since ORT does not consider the internal files between e.g. analyzer step and the scanner step, or scanner step and evaluator step, as interfaces but as internal communications structures that can be changed in a breaking way. On the other hand, the introduction of third party scanners as scanner classes, is considered (more) as an interface.
